export const REMARKS_DATABASE: Record<string, string[]> = {
  "KCDC": [
    "ATTENDED 0800-1700 DAILY, FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL SELF-SERVE AND JET A FULL-SERVE. CALL OUT FOR FUEL AVAILABLE.",
    "HIGH ELEVATION AIRPORT (5622 FT MSL). PERFORMANCE CONSIDERATIONS CRITICAL.",
    "MOUNTAIN FLYING ENVIRONMENT. TURBULENCE AND STRONG WINDS POSSIBLE, ESPECIALLY IN AFTERNOONS.",
    "WILDLIFE ALERT: DEER AND ELK ON AND IN VICINITY OF AIRPORT, ESPECIALLY AT DAWN/DUSK.",
    "COMMERCIAL AIR SERVICE AVAILABLE. CAUTION FOR JET BLAST AND WAKE TURBULENCE.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 7000 FT MSL (1378 FT AGL)."
  ],
  "1L7": [
    "CLOSED INDEFINITELY. FORMERLY ST. GEORGE MUNICIPAL AIRPORT.",
    "NEW ST. GEORGE REGIONAL AIRPORT (KSGU) IS NOW THE PRIMARY AIRPORT FOR THE REGION.",
    "AIRFIELD REMAINS PARTIALLY MARKED BUT IS NOT FOR AVIATION USE.",
    "NO SERVICES AVAILABLE."
  ],
  "1L8": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 6632 FT MSL. DENSITY ALTITUDE MAY BE SIGNIFICANT.",
    "RUNWAY 01/19 IS PAVED, BUT MAY HAVE CRACKS AND PATCHES. ADVISE CAUTION.",
    "WILDLIFE ALERT: DEER COMMONLY ON OR NEAR RUNWAYS, ESPECIALLY AT DAWN/DUSK.",
    "NO WINTER MAINTENANCE. EXPECT SNOW AND ICE CONDITIONS NOVEMBER TO MARCH.",
    "FOR FUEL, CONTACT KCDC OR KBCE. TRANSPORTATION NOT AVAILABLE."
  ],
  "1L9": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 7009 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 16/34 IS UNPAVED (GRADED DIRT/GRAVEL). CONDITIONS VARY WITH WEATHER.",
    "WILDLIFE ALERT: DEER AND SMALL ANIMALS COMMONLY ON OR NEAR RUNWAYS.",
    "MOUNTAINOUS TERRAIN ALL QUARTERS. CAUTION FOR UP/DOWNDRAFTS AND TURBULENCE.",
    "CHECK NOTAMS FOR CURRENT FIELD CONDITIONS PRIOR TO ARRIVAL."
  ],
  "U52": [
    "ATTENDED INTERMITTENTLY, GENERALLY 0900-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "ACTIVE SKYDIVING OPERATIONS. CHECK NOTAMS AND MONITOR CTAF 122.9.",
    "CAUTION FOR PARACHUTISTS AND JUMP AIRCRAFT IN VICINITY OF AIRPORT.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 4900 FT MSL (1200 FT AGL).",
    "STRONG CROSSWINDS CAN BE A FACTOR, ESPECIALLY ON RUNWAY 13/31."
  ],
  "KFOM": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 4976 FT MSL. DENSITY ALTITUDE MAY BE A FACTOR IN SUMMER.",
    "RUNWAY 17/35 IS UNPAVED (GRADED DIRT). CONDITIONS VARY WITH WEATHER. PPR RECOMMENDED.",
    "WILDLIFE ALERT: DEER AND COYOTES COMMONLY ON OR NEAR RUNWAYS.",
    "CTAF 122.9. ADVISE OF INTENTIONS.",
    "NO RESTROOMS OR SHELTER AVAILABLE. REMOTE LOCATION."
  ],
  "KMLF": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 4616 FT MSL. TURF RUNWAY 16/34.",
    "RUNWAY CONDITIONS VARY GREATLY WITH PRECIPITATION. AVOID SOFT SPOTS.",
    "WILDLIFE ALERT: DEER, BIRDS, AND SMALL ANIMALS COMMONLY ON OR NEAR RUNWAYS.",
    "NO WINTER MAINTENANCE. EXPECT SNOW AND ICE CONDITIONS NOVEMBER TO APRIL.",
    "CTAF 122.9. ADVISE OF INTENTIONS."
  ],
  "KBCE": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1800 LOCAL (SEASONAL). CALL AHEAD FOR FUEL.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "HIGH ELEVATION AIRPORT (7586 FT MSL). SIGNIFICANT DENSITY ALTITUDE CONSIDERATIONS.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING BRYCE CANYON NATIONAL PARK BELOW 10,000 FT MSL.",
    "WILDLIFE ALERT: DEER, ELK, AND OTHER WILDLIFE ON OR NEAR AIRPORT PROPERTY.",
    "SEASONAL COMMERCIAL SERVICE. CAUTION FOR JET BLAST AND WAKE TURBULENCE."
  ],
  "KSGU": [
    "ATTENDED DAILY 0700-2000 LOCAL. FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "MOUNTAIN FLYING ENVIRONMENT. CAUTION FOR TURBULENCE AND STRONG WINDS, ESPECIALLY DURING SUMMER MONSOONS.",
    "WILDLIFE ALERT: BIRDS AND RABBITS COMMONLY IN THE VICINITY OF THE AIRFIELD.",
    "COMMERCIAL AIR SERVICE. CAUTION FOR JET BLAST AND WAKE TURBULENCE ON MAIN RUNWAY.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 4600 FT MSL (1300 FT AGL)."
  ],
  "KSLC": [
    "CLASS B AIRSPACE. ALL AIRCRAFT MUST HAVE ATC CLEARANCE TO ENTER.",
    "ALL SERVICES AVAILABLE, INCLUDING FULL MAINTENANCE AND DE-ICING CAPABILITIES.",
    "MAJOR AIRLINE HUB. EXPECT HIGH VOLUME OF COMMERCIAL AND GA TRAFFIC.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID UNNECESSARY OVERFLIGHTS OF RESIDENTIAL AREAS.",
    "WILDLIFE MANAGEMENT PROGRAM IN EFFECT. CAUTION FOR BIRDS, ESPECIALLY NEAR GREAT SALT LAKE.",
    "MULTIPLE PARALLEL RUNWAYS. CONFIRM RUNWAY ASSIGNMENT WITH ATC."
  ],
  "KPVU": [
    "ATTENDED DAILY 0700-2200 LOCAL. FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "ACTIVE FLIGHT TRAINING AND SKYDIVING OPERATIONS. MONITOR CTAF 122.9 FOR SKYDIVE OPS.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING BYU AND RESIDENTIAL AREAS.",
    "MOUNTAINOUS TERRAIN TO THE EAST. CAUTION FOR OROGRAPHIC TURBULENCE AND DOWNDRAFTS.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5000 FT MSL (1300 FT AGL)."
  ],
  "KHND": [
    "ATTENDED 24 HOURS. FULL FBO SERVICES, MAINTENANCE, AND RENTAL CARS AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. CALL FOR REFUELING.",
    "BUSY CORPORATE AND GENERAL AVIATION AIRPORT. EXPECT MIX OF TRAFFIC.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING RESIDENTIAL AREAS.",
    "DESERT ENVIRONMENT. EXPECT HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "CAUTION: RAPIDLY DEVELOPING THUNDERSTORMS DURING SUMMER MONSOON SEASON."
  ],
  "KVGT": [
    "ATTENDED 24 HOURS. FULL FBO SERVICES, MAINTENANCE, AND FLIGHT TRAINING.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "EXTREMELY BUSY FLIGHT TRAINING OPERATIONS. EXPECT HIGH VOLUME OF TOUCH-AND-GOES AND PATTERN WORK.",
    "NEAR NELLIS AFB AIRSPACE. MAINTAIN STRICT ADHERENCE TO ATC INSTRUCTIONS.",
    "DESERT ENVIRONMENT. EXPECT HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING RESIDENTIAL AREAS."
  ],
  "KOGD": [
    "ATTENDED DAILY 0600-2200 LOCAL. FBO SERVICES, MAINTENANCE, AND FLIGHT TRAINING.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "HOME TO AIR NATIONAL GUARD OPERATIONS. CAUTION FOR MILITARY AIRCRAFT AND HIGH-PERFORMANCE JETS.",
    "MOUNTAINOUS TERRAIN TO THE EAST. CAUTION FOR OROGRAPHIC TURBULENCE AND DOWNDRAFTS.",
    "WILDLIFE ALERT: BIRDS AND SMALL ANIMALS ON OR NEAR AIRFIELD.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5000 FT MSL (1200 FT AGL)."
  ],
  "KPGA": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0700-1800 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "TOURIST DESTINATION FOR LAKE POWELL/ANTELOPE CANYON. EXPECT SCENIC FLIGHT TRAFFIC.",
    "HIGH DESERT ENVIRONMENT. EXPECT STRONG WINDS AND TURBULENCE, ESPECIALLY IN AFTERNOONS.",
    "WILDLIFE ALERT: RABBITS AND BIRDS COMMONLY ON OR NEAR AIRPORT.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5500 FT MSL (1400 FT AGL)."
  ],
  "KGCN": [
    "ATTENDED DAILY 0700-1900 LOCAL. FBO SERVICES AND LIMITED MAINTENANCE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "EXTREMELY HIGH VOLUME OF VFR TOURIST FLIGHTS. CAUTION FOR CONFLICTING TRAFFIC.",
    "SPECIAL FLIGHT RULES AREA (SFRA) OVER GRAND CANYON. REVIEW FAR 91 SUBPART U.",
    "NOISE ABATEMENT PROCEDURES STRICTLY ENFORCED. AVOID OVERFLYING CANYON BELOW 10,000 FT MSL.",
    "HIGH ELEVATION AIRPORT (6606 FT MSL). PERFORMANCE CONSIDERATIONS ARE CRITICAL."
  ],
  "KKNB": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 3582 FT MSL. RUNWAY 14/32 IS PAVED WITH CRACKS AND PATCHES.",
    "WILDLIFE ALERT: DEER AND JAVELINA COMMONLY ON OR NEAR RUNWAYS, ESPECIALLY AT DAWN/DUSK.",
    "REMOTE LOCATION. NO COURTESY CAR OR FUEL AVAILABLE.",
    "CTAF 122.9. ADVISE OF INTENTIONS.",
    "MOUNTAINOUS TERRAIN TO THE NORTH AND EAST."
  ],
  "KBDG": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 5800 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 17/35 IS PAVED, BUT MAY HAVE CRACKS AND LOOSE DEBRIS. CHECK NOTAMS.",
    "WILDLIFE ALERT: DEER AND ELK COMMONLY ON OR NEAR RUNWAYS, ESPECIALLY AT DAWN/DUSK.",
    "REMOTE LOCATION. NO COURTESY CAR OR FUEL AVAILABLE.",
    "MOUNTAINOUS TERRAIN. CAUTION FOR UP/DOWNDRAFTS AND TURBULENCE."
  ],
  "KCNY": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "TOURIST DESTINATION FOR ARCHES/CANYONLANDS NATIONAL PARKS. EXPECT SCENIC FLIGHT TRAFFIC.",
    "MOUNTAINOUS TERRAIN. CAUTION FOR UP/DOWNDRAFTS AND TURBULENCE, ESPECIALLY IN AFTERNOONS.",
    "WILDLIFE ALERT: RABBITS AND SMALL ANIMALS COMMONLY ON OR NEAR AIRPORT.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5000 FT MSL (1000 FT AGL)."
  ],
  "KPUC": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "HIGH ELEVATION AIRPORT (5730 FT MSL). DENSITY ALTITUDE MAY BE SIGNIFICANT.",
    "WILDLIFE ALERT: DEER AND COYOTES COMMONLY ON OR NEAR RUNWAYS.",
    "CTAF 122.9. ADVISE OF INTENTIONS.",
    "REMOTE LOCATION. LIMITED GROUND TRANSPORTATION AVAILABLE."
  ],
  "KBMC": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0900-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "ACTIVE AGRICULTURAL OPERATIONS. CAUTION FOR SPRAY AIRCRAFT IN VICINITY.",
    "WILDLIFE ALERT: PHEASANTS AND OTHER BIRDS COMMONLY ON OR NEAR RUNWAYS.",
    "NEAR WASATCH MOUNTAINS. CAUTION FOR OROGRAPHIC TURBULENCE AND DOWNDRAFTS.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 4900 FT MSL (1100 FT AGL)."
  ],
  "KBTF": [
    "ATTENDED DAILY 0800-1800 LOCAL. FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "VERY ACTIVE SKYDIVING OPERATIONS. EXTREME CAUTION FOR PARACHUTISTS AND JUMP AIRCRAFT.",
    "GRAND CANYON TOURIST FLIGHTS ORIGINATE HERE. EXPECT HIGH VOLUME OF VFR TRAFFIC.",
    "DESERT ENVIRONMENT. EXPECT HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING RESIDENTIAL AREAS."
  ],
  "KENV": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "HISTORICAL WWII TRAINING BASE (ENOLA GAY HOME BASE). AIRFIELD MAY HAVE OLD REMAINS.",
    "REMOTE DESERT ENVIRONMENT. EXPECT HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "WILDLIFE ALERT: COYOTES AND JACKRABBITS COMMONLY ON OR NEAR RUNWAYS.",
    "CTAF 122.9. ADVISE OF INTENTIONS."
  ],
  "KRIF": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "HIGH ELEVATION AIRPORT (5347 FT MSL). DENSITY ALTITUDE MAY BE SIGNIFICANT.",
    "ACTIVE AGRICULTURAL OPERATIONS. CAUTION FOR SPRAY AIRCRAFT IN VICINITY.",
    "WILDLIFE ALERT: DEER AND SMALL ANIMALS COMMONLY ON OR NEAR RUNWAYS.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 6200 FT MSL (853 FT AGL)."
  ],
  "KAZC": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 4935 FT MSL. HIGH DESERT ENVIRONMENT.",
    "RUNWAY 16/34 IS PAVED, BUT MAY HAVE CRACKS AND DEBRIS. CHECK NOTAMS.",
    "WILDLIFE ALERT: DEER AND COYOTES COMMONLY ON OR NEAR RUNWAYS, ESPECIALLY AT DAWN/DUSK.",
    "REMOTE LOCATION. NO COURTESY CAR OR FUEL AVAILABLE.",
    "MOUNTAINOUS TERRAIN TO THE EAST AND SOUTH."
  ],
  "KBDU": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. FBO SERVICES AVAILABLE.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "ACTIVE FLIGHT TRAINING. EXPECT HIGH VOLUME OF PATTERN WORK AND LOCAL FLIGHTS.",
    "NOISE SENSITIVE AREA. STRICT NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID OVERFLYING RESIDENTIAL AREAS.",
    "MOUNTAIN WAVE TURBULENCE COMMON. CAUTION FOR STRONG WINDS AND SHEAR, ESPECIALLY IN WINTER.",
    "WILDLIFE ALERT: DEER, FOX, AND PRAIRIE DOGS COMMONLY ON OR NEAR AIRFIELD."
  ],
  "KHCR": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION APPROXIMATELY 7500 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 10/28 IS UNPAVED (GRAVEL/DIRT). CONDITIONS VARY GREATLY WITH WEATHER.",
    "WILDLIFE ALERT: DEER, ELK, AND MOOSE COMMONLY ON OR NEAR RUNWAYS.",
    "MOUNTAINOUS TERRAIN ALL QUARTERS. CAUTION FOR UP/DOWNDRAFTS AND TURBULENCE.",
    "CHECK NOTAMS FOR CURRENT FIELD CONDITIONS. RECOMMENDED PPR FOR USE."
  ],
  "KLGU": [
    "ATTENDED DAILY 0700-1900 LOCAL. FBO SERVICES, MAINTENANCE, AND FLIGHT TRAINING.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "MOUNTAIN FLYING ENVIRONMENT. CAUTION FOR OROGRAPHIC TURBULENCE AND DOWNDRAFTS FROM WASATCH RANGE.",
    "ACTIVE UNIVERSITY FLIGHT TRAINING PROGRAM. EXPECT HIGH VOLUME OF PATTERN WORK.",
    "WILDLIFE ALERT: DEER, PHEASANTS, AND WATERFOWL COMMONLY ON OR NEAR AIRFIELD.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5500 FT MSL (1200 FT AGL)."
  ],
  "U77": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 4976 FT MSL. DENSITY ALTITUDE MAY BE A FACTOR IN SUMMER.",
    "RUNWAY 04/22 IS UNPAVED (GRADED DIRT). CONDITIONS VARY WITH WEATHER. PPR RECOMMENDED.",
    "WILDLIFE ALERT: DEER AND COYOTES COMMONLY ON OR NEAR RUNWAYS.",
    "CTAF 122.9. ADVISE OF INTENTIONS.",
    "REMOTE LOCATION. NO RESTROOMS OR SHELTER AVAILABLE."
  ],
  "KTVY": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "ACTIVE AGRICULTURAL OPERATIONS. CAUTION FOR SPRAY AIRCRAFT IN VICINITY.",
    "NEAR DUGWAY PROVING GROUND (MILITARY TEST RANGE). AVOID RESTRICTED AIRSPACE.",
    "WILDLIFE ALERT: JACKRABBITS AND COYOTES COMMONLY ON OR NEAR AIRFIELD.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5500 FT MSL (1200 FT AGL)."
  ],
  "KEVW": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "HIGH ELEVATION AIRPORT (7214 FT MSL). SIGNIFICANT DENSITY ALTITUDE CONSIDERATIONS.",
    "WINTER CONDITIONS: EXPECT SNOW AND ICE NOVEMBER TO APRIL. CHECK NOTAMS FOR PLOWING.",
    "WILDLIFE ALERT: DEER AND PRONGHORN COMMONLY ON OR NEAR AIRPORT.",
    "MOUNTAINOUS TERRAIN TO THE EAST AND SOUTH."
  ],
  "U14": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 5530 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 03/21 IS UNPAVED (DIRT/GRAVEL). CONDITIONS VARY GREATLY WITH WEATHER.",
    "SCENIC FLIGHTS IN VICINITY. CAUTION FOR CONFLICTING VFR TRAFFIC.",
    "REMOTE LOCATION. NO FACILITIES OR SHELTER. PPR RECOMMENDED.",
    "WILDLIFE ALERT: DEER, HORSES, AND CATTLE ON OR NEAR AIRFIELD."
  ],
  "U96": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "TOURIST DESTINATION FOR ZION/BRYCE CANYON. EXPECT SCENIC FLIGHT TRAFFIC.",
    "HIGH DESERT ENVIRONMENT. EXPECT STRONG WINDS AND TURBULENCE, ESPECIALLY IN AFTERNOONS.",
    "WILDLIFE ALERT: DEER AND RABBITS COMMONLY ON OR NEAR AIRFIELD.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5500 FT MSL (1100 FT AGL)."
  ],
  "KIFP": [
    "ATTENDED DAILY 0700-1900 LOCAL. FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "COMMERCIAL SERVICE (SEASONAL/CHARTER). CAUTION FOR JET BLAST AND WAKE TURBULENCE.",
    "DESERT ENVIRONMENT. EXPECT EXTREME HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "CLOSE PROXIMITY TO LAUGHLIN CASINOS. EXPECT TOURIST-RELATED TRAFFIC.",
    "WILDLIFE ALERT: COYOTES AND JACKRABBITS COMMONLY ON OR NEAR AIRFIELD."
  ],
  "U64": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 4819 FT MSL. PAVED RUNWAY 17/35. CHECK FOR CRACKS/DEBRIS.",
    "EXTREMELY HIGH VOLUME OF VFR TOURIST FLIGHTS TO GRAND CANYON WEST (SKYWALK).",
    "SPECIAL FLIGHT RULES AREA (SFRA) NEARBY. REVIEW FAR 91 SUBPART U. CAUTION FOR CONFLICTING TRAFFIC.",
    "NOISE ABATEMENT PROCEDURES IN EFFECT. AVOID UNNECESSARY OVERFLIGHTS OF RESORT AREAS.",
    "REMOTE LOCATION. EXPECT LIMITED EMERGENCY SERVICES. MANAGER CONTACT AVAILABLE VIA INFO SIGN."
  ],
  "KSPK": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 5800 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 16/34 IS UNPAVED (GRADED DIRT/GRAVEL). CONDITIONS VARY WITH WEATHER.",
    "WILDLIFE ALERT: DEER AND PRONGHORN COMMONLY ON OR NEAR RUNWAYS.",
    "REMOTE LOCATION. NO COURTESY CAR OR FUEL AVAILABLE.",
    "CHECK NOTAMS FOR CURRENT FIELD CONDITIONS PRIOR TO ARRIVAL."
  ],
  "KDTA": [
    "ATTENDED INTERMITTENTLY, TYPICALLY 0800-1700 LOCAL. CALL AHEAD FOR SERVICES.",
    "FUEL: 100LL SELF-SERVE AVAILABLE 24/7. JET A BY ARRANGEMENT.",
    "ACTIVE AGRICULTURAL OPERATIONS. CAUTION FOR SPRAY AIRCRAFT IN VICINITY.",
    "WILDLIFE ALERT: PHEASANTS AND OTHER BIRDS COMMONLY ON OR NEAR AIRFIELD.",
    "FLAT TERRAIN. EXPECT STRONG WINDS AND DUST DEVILS DURING HOT WEATHER.",
    "PREFERRED VFR TRAFFIC PATTERN ALTITUDE 5500 FT MSL (1200 FT AGL)."
  ],
  "41U": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION 5800 FT MSL. HIGH DENSITY ALTITUDE OPERATIONS.",
    "RUNWAY 17/35 IS PAVED, BUT MAY HAVE CRACKS AND LOOSE DEBRIS. CHECK NOTAMS.",
    "WILDLIFE ALERT: DEER AND ELK COMMONLY ON OR NEAR RUNWAYS, ESPECIALLY AT DAWN/DUSK.",
    "REMOTE LOCATION. NO COURTESY CAR OR FUEL AVAILABLE.",
    "MOUNTAINOUS TERRAIN. CAUTION FOR UP/DOWNDRAFTS AND TURBULENCE."
  ],
  "IGM": [
    "ATTENDED DAILY 0800-1700 LOCAL. FBO SERVICES AND MAINTENANCE AVAILABLE.",
    "FUEL: 100LL AND JET A AVAILABLE. SELF-SERVE 100LL 24/7.",
    "MAJOR AIRCRAFT STORAGE AND RECYCLING FACILITY. CAUTION FOR LARGE, STATIC AIRCRAFT.",
    "HISTORIC WWII TRAINING BASE. RUNWAYS ARE WIDE AND LONG.",
    "DESERT ENVIRONMENT. EXPECT HIGH TEMPERATURES AND DENSITY ALTITUDE CONCERNS IN SUMMER.",
    "WILDLIFE ALERT: COYOTES AND JACKRABBITS COMMONLY ON OR NEAR AIRFIELD."
  ],
  "K67L": [
    "UNATTENDED AIRPORT. NO SERVICES AVAILABLE. PILOTS USE CAUTION.",
    "FIELD ELEVATION APPROXIMATELY 3700 FT MSL. REMOTE LOCATION.",
    "RUNWAY 01/19 IS UNPAVED (GRADED DIRT/GRAVEL). CONDITIONS VARY WITH WEATHER.",
    "PROXIMITY TO COLORADO RIVER AND GRAND CANYON. SCENIC FLIGHTS IN VICINITY.",
    "WILDLIFE ALERT: DEER, COYOTES, AND RAPTORS COMMONLY ON OR NEAR AIRFIELD.",
    "NO FACILITIES OR SHELTER. MINIMUM ACCESS TO SERVICES."
  ]
};
