export const REMARKS_DATABASE: Record<string, string[]> = {
  KCDC: [
    "GA ACFT NOT PERMITTED ON ACR RAMP.",
    "AUTOROTATE - NO AUTOROTATION TRNG TO HELIPAD. RWY 02/20 CLSD TO HEL RUN-ON LNDG; RWY 08/26 CLSD TO HEL RUN-ON LNDG; TWY A, N OF RWY 8/26 CLSD TO HEL RUN-ON LNDG; TWY C CLSD TO HEL RUN-ON LNDG.",
    "RWY 02 LEFT TRAFFIC PATTERN EXC HELICOPTERS. RWY 20 RIGHT TRAFFIC EXC HELICOPTERS.",
    "FOR CD IF UNA TO CTC ON FSS FREQ, CTC SALT LAKE ARTCC AT 801-320-2568.",
    "RWY 2/20, A, A1-A4, C FM A TO TRML & TRML APN AVBL TO ACRS.",
    "RECOMMNED PILOTS CIRCLE ARPT FOR ALT BEFORE DEPARTING EASTBOUND DUE TO FAST RISING TERRAIN AND HI DENSITY ALT. TURBC LIKELY INVOF MNTS & PASSES.",
    "DESIGNATED CALM WIND RWY (BLW 5 KTS) IS RWY 20, RGT TFC.",
    "UNMON SFC CONDS 1900-0700 DLY EXC FOR SKED ACR.",
    "EXTENSIVE HELICOPTER ACTIVITY.",
    "EXTENSIVE FLIGHT TRNG INVOF ARPT.",
    "OLL 100LL FUEL AVBL 24 HRS SELF-SVC CREDIT CARD SYSTEM.",
    "ACTVT MALSR RWY 20; REIL RWY 02, 08 & 26; HIRL RWY 02/20; MIRL RWY 08/26 - CTAF. PAPI RWY 02 & 20, 08 OPER CONSLY."
  ],
  '1L7': [
    "DEER & COYOTES ON & INVOF RWY.",
    "RWY 13/31 SLGTLY OVRGROWN WITH BRUSH IN CRACK S.",
    "FOR CUSTOM SEV RUNWAY IN SPR/SUM PLS CTC AIRPORT MGR.",
    "SELF-SERVE 100LL AVAILABLE 24 HOURS CARDS ACCEPTED.",
    "CTAF/UNICOM 122.9 UNMONITORED."
  ],
  '1L8': [
    "EXTENSIVE ULTRALIGHT & POWERED PARACHUTE OPERATIONS ON & INVOF RWY.",
    "RWY 01 HAS 10-15 FT HIGH DITCH AT SOUTH END. OBTAIN LOCAL BRIEFING BEFORE FIRST LANDING.",
    "WIND CONDS VARY GRTLY FROM SGU ASOS; CHK WIND SOCK DIRECTLY.",
    "INTENSE HELICOPTER & FIX-WING OPERATIONS IN SOUTH PATTERN AREA."
  ],
  '1L9': [
    "DEER ON IN VICINITY OF RWY ESPECIALLY DAWN & DUSK.",
    "GLIDER ACTIVITY INTENSE FROM MAY TO SEPTEMBER.",
    "SELF-SERVE 100LL AVAILABLE 24/7.",
    "RWY 04/22 SLIGHT GRADIENT DECREASING TO THE SOUTH."
  ],
  U52: [
    "COYOTES, RABBITS & SWIFT BIRDS INVOF RUNWAY.",
    "RWY 07/25 GRADIENT INCREASES AT WEST END.",
    "SFC LOOSE GRAVEL & CHIPS ON BOTH RWYS AND TAXIWAYS.",
    "EXTENSIVE TRAINING ACTIVITY FROM LOCAL SUU HELICOPTER FLIGHT SCHOOL."
  ],
  KFOM: [
    "DEER ON & INVOF RUNWAYS IN FALL & WINTER.",
    "LIGHTS ACTVT ON CTAF 122.8.",
    "SFC CONDS UNMONITORED; LCL BRIEFING ADVISED."
  ],
  KMLF: [
    "DEER & ANTELOPE INVOF RWY DUSK TO DAWN.",
    "RWY 16 HAS SIGNIFICANT SWELL IN MIDDLE SECTION.",
    "MILITARY HELICOPTER AND JET AIRSPACE OVERHEAD."
  ],
  KBCE: [
    "DEER ON & INVOF RUNWAY.",
    "AIRPORT LANDS RESTRICTED TO CERTIFIED OPERATORS DURING WILDLIFE CONDS.",
    "HIGH DENSITY ALTITUDE ADVISEMENTS CONSTANTLY IN EFFECT."
  ],
  KSGU: [
    "COMMERCIAL TERMINAL RAMP RESTRICTED.",
    "MANDATORY COOPERATIVE TRAFFIC PATTERNS OVER SANTA CLARA CO-OP INTERSECTION.",
    "WIND SHEAR ADVISORIES ACTIVE OVER NORTH RIDGE."
  ],
  KSLC: [
    "CLASS B AIRSPACE PRIMARY.",
    "DEER AND WATERFOWL IN VICINITY OF RUNWAY.",
    "ASOS WEATHER BROADCAST ON ATIS FREQUENCY 124.75 OR BY PHONE 801-524-4000.",
    "HEAVY CIVILIAN AND MILITARY HELICOPTER TRAINING WITHIN 30 NM.",
    "RUNWAY 34R/16L USES STANDARD RIGHT TRAFFIC PATTERN.",
    "ALL DEPARTING AIRCRAFT CONTACT EXPEDITED GROUND BEFORE TAXI."
  ],
  KPVU: [
    "INTENSE FLIGHT TRAINING AND STUDENT SOLO ACTIVITY.",
    "CONTROL TOWER OPERATES DAILY FROM 0600-2200 LOCAL.",
    "DEER ON & INVOF RUNWAYS.",
    "CTAF/UNICOM FREQUENCY IS 122.8 WHEN TOWER IS CLOSED.",
    "SFC CONDITIONS UNMONITORED OUTSIDE TOWER HOURS."
  ],
  KHND: [
    "AIRFIELD RESTRICTED TO AIRCRAFT OVER 80,000 LBS MAX CERTIFICATED WEIGHT.",
    "NOISE ABATEMENT PROCEDURES COMPULSORY; CONTACT DEPARTMENTS OR FBO PRIOR TO TAKEOFF.",
    "INTENSE TURBINE FLIGHT TRAINING AND AIR TOUR HELICOPTER CORRIDORS N/E.",
    "PAPI RWY 35L & 35R OPERATE CONTINUOUSLY.",
    "SFC LOOSE COMPACTED GRAVEL OUTSIDE TERMINAL APRONS."
  ],
  KVGT: [
    "INTENSE FLIGHT TRAINING; EXTREME STUDENT PILOT CONGESTION.",
    "CLASS D AIRSPACE ACTIVE 0600-2200 LOCAL.",
    "ALERT FOR DEER/YOTE ANIMAL ENTRANCES ALONG WEST PERIMETER FENCE.",
    "CALM WIND RUNWAY IS RWY 12R. RIGHT TRAFFIC FOR 12R & 30R.",
    "MIDGET RECREATIONAL AIRSTRIP IN VICINITY NORTH."
  ],
  KOGD: [
    "MIGRATORY BIRDS INVOF RUNWAYS SPRING AND FALL.",
    "AERODROME SURFACE CONDITIONS UNMONITORED BETWEEN 2200-0600 LOCAL.",
    "INTENSE HELICOPTER AND FIXED-WING DUAL TRAINING FROM ADJACENT SCHOOL CO-OPS.",
    "AWOS BROADCAST ON 125.55 OPERATING CONTINUOUSLY."
  ],
  KPGA: [
    "AIRPORT ADJACENT TO HIGH VERTICAL CLIFFS OF GLEN CANYON NATIONAL RECREATION AREA.",
    "COYOTE AND DEER HAZARDS ON RUNWAYS DAWN & DUSK.",
    "SELF-SERVE 100LL FUEL AVAILABLE 24/7/365.",
    "WIND SHEAR EXPERIENCED ON RWY 30 DURING GUSTY SOUTHWEST WINDS."
  ],
  KGCN: [
    "STRICT GRAND CANYON SFRA NOISE-ABATEMENT AND MANDATORY REPORTING FLIGHT PLAN PROCEDURES IN EFFECT.",
    "ELK AND DEER HAZARDS ON AND IN VICINITY OF RUNWAYS DAWN TO DUSK.",
    "HIGH DENSITY ALTITUDE ADVISORY CONSTANT DURING SUMMER MONTHS.",
    "COMMERCIAL AIR TOUR CORRIDORS DESIGNATED OVERHEAD."
  ],
  KKNB: [
    "DEER ON RUNWAY DURING LOW-LIGHT AND NIGHT HOURS.",
    "HIGH RISING MOUNTAIN TERRAIN IMMEDIATELY NORTH AND EAST.",
    "SELF-SERVE 100LL FUEL AVAILABLE 24/7 VIA CARD.",
    "WIND CONDS UNRELIABLE; RE-CHECK WINDSOCK DIRECTLY."
  ],
  KBDG: [
    "DEER ON AND IN VICINITY OF RUNWAYS ESPECIALLY DAWN & DUSK.",
    "SELF-SERVE CREDIT CARD FUEL SYSTEM OPEN 24 HOURS.",
    "SURFACE CONDITIONS UNMONITORED OUTSIDE REGULAR BUSINESS HOURS."
  ],
  KCNY: [
    "INTENSE GLIDER, CHARTER AND ULTRALIGHT ACTIVITY.",
    "WATERFOWL AND DEER ON RUNWAYS.",
    "SURFACE CONDITIONS MONITORED EXCLUSIVELY DURING CARRIER SCHEDULE SCHEDULES.",
    "WIND SHEAR ON SHORT FINAL FOR RWY 03."
  ],
  KPUC: [
    "RUNWAY 01/19 HAS SIGNIFICANT CRACK SEALS ALONG CENTERLINE.",
    "DEER AND WILDLIFE ON RUNWAY DAWN TO DUSK.",
    "SELF-SERVE 100LL FUEL AVAILABLE 24 HOURS VIA CARD SYSTEM."
  ],
  KBMC: [
    "FREQUENT AGRICULTURAL SPRAYER AND GLIDER INVIC OPERATORS.",
    "SURFACE CONDITIONS UNMONITORED NIGHT HOURS.",
    "DEER AND OTHER WILD ANIMALS REPORTED ON FIELD."
  ],
  KBTF: [
    "RESIDENTIAL DEVELOPMENTS SURROUND AIRPORT; STRICT VOLUNTARY NOISE ABATEMENT.",
    "RUNWAY 17/35 IS NARROW WITH CLOSE TAXIWAYS.",
    "INDUSTRIAL CRANES TO THE SOUTH END OF THE FIELD."
  ],
  KENV: [
    "HISTORIC AIRFIELD WITH LOOSE DUST/GRAVEL REMNANTS ON TAXIWAY B.",
    "EXTREME WIND GUSTS COMMON ACROSS THE SALT FLATS.",
    "CHECK NOTAMS FOR INTERMITTENT RUNWAY CLOSURES DURING MILITARY OPS."
  ],
  KRIF: [
    "DEER ON AND IN VICINITY OF RWY DUSK TO DAWN.",
    "MODERATE TO SEVERE TURBULENCE LIKELY INVOF HIGH TERRAIN EAST.",
    "SELF-SERVE 100LL FUEL ISLAND IS FULLY FUNCTIONAL 24/7."
  ],
  KAZC: [
    "DEER ON RUNWAY DAWN AND NIGHT.",
    "SELF-SERVE 100LL AVAILABLE.",
    "CTAF/UNICOM 122.9 UNMONITORED FIELD CONDS."
  ],
  KBDU: [
    "GLIDER TOWING AND ULTRALIGHT ACTIVITY INTENSE WEEKENDS.",
    "STRICT NOISE ABATEMENT OVER HISTORIC DOWNTOWN AREA.",
    "HIGH DENSITY ALTITUDE DURING HOT SUMMER DAYS."
  ],
  KHCR: [
    "MANDATORY COOPERATIVE REPORTING FREQUENCY 122.8.",
    "DEER AND ELK ON AND IN VICINITY OF RUNWAYS DAWN & DUSK.",
    "HIGH ELEVATION AND RAPIDLY MOUNTING EASTERN TERRAIN."
  ],
  KLGU: [
    "AGRICULTURAL SPRAYERS OPERATE FROM AIRPORT DURING SEASON.",
    "GLIDER AND WINCH LAUNCH OPERATIONS FREQUENT FROM MAY TO OCT.",
    "SFC CONDITIONS UNMONITORED DURING NIGHT HOURS."
  ],
  U77: [
    "OBTAIN LOCAL OR FLIGHT SERVICE BRIEFING BEFORE FLYING.",
    "SOFT SURFACE GRAVEL AND DIRT PREVENT HEAVIER ARRIVALS.",
    "SHEEP AND DEER ON RUNWAY DAWN TO DUSK."
  ],
  KTVY: [
    "MILITARY HELICOPTERS FROM TOOELE RECREATIONAL CORRIDOR.",
    "DEER ON AND IN VICINITY OF RUNWAY DAWN AND NIGHT.",
    "WINDSHEAR EXPERIENCED ON COLD REAR-WIND FRONTS."
  ],
  KEVW: [
    "FREQUENT MILITARY OPERATIONS COMPRISING JET FIGHTERS AND TRANSPORTS.",
    "WILDLIFE IN VICINITY OF RUNWAY ALL SEASONS.",
    "SELF-SERVE FUEL ISLAND FULLY OPERATIONAL WITH CREDIT CARD."
  ],
  U14: [
    "UNMONITORED SERVICE STATION CONDS.",
    "WILDLIFE ON FIELD ESPECIALLY ELK/DEER HARASSMENT.",
    "SAND AND LOOSE GRAVEL TO CORNERS."
  ],
  U96: [
    "CAUTION UNMARKED OBSTACLES IN GENERAL FLIGHT PLANE.",
    "WIND CONDITIONS SHIFT RAPIDLY DUE TO REAR CANYON DRAFT.",
    "SELF-SERVE FOR LOCAL RE-FUEL PATRONS ONLY."
  ],
  KIFP: [
    "COMMERCIAL CARRIER TRAFFIC PATTERNS CONGESTED.",
    "BIRD HAZARDS ACROSS RIVERS ACCUMULATING SOUTH.",
    "PAPI RWY 16 & 34 ON ALL-HOURS METROPOLITAN OPERATOR."
  ],
  U64: [
    "DIRT RUNWAY HAS UNMARKED SWELLS AFTER RAINFALL.",
    "ANIMALS AND LIVESTOCK ON RUNWAY ZONE.",
    "DEPARTURE TO NORTH ADVISABLE DUE TO TERRAIN."
  ],
  KSPK: [
    "SFC RUNWAYS DEVIATIONS UNMONITORED.",
    "DEER HAZARDS DURING WINTER RECREATIONAL MONTHS.",
    "SELF-SERVE CREDIT CARD MACHINE FUNCTIONING."
  ],
  KDTA: [
    "UTILITY GLIDERS LAUNCH FROM RUNWAY ALIGNED PARALLEL.",
    "UNCONVENTIONAL AGRICULTURAL VEHICLES IN ADJACENT TAXI CORRIDORS.",
    "DEER ON RUNWAY."
  ],
  "41U": [
    "GRAVEL RUNWAY WELL COMPACTED BUT CHIPS COMMON.",
    "ANIMALS ON FIELD REGULARLY.",
    "PREFER RE-FUEL OUT OF MAIN REGIONAL CENTER."
  ],
  IGM: [
    "CLASS D AIRSPACE ACTIVE DURING daylight TRAINING SCHEDULES.",
    "MILITARY ROTOR OPS ON PERIMETER TAXIWAYS.",
    "DEER AND WILDLIFE SIGHTED ON FIELDS."
  ],
  K67L: [
    "DEER ON RUNWAY ALL SEASONS.",
    "SELF-SERVE LL100 POWERED FOR INSTRUCTORS.",
    "UNSHELTERED COLD FRONT WINDS EXTREME."
  ],
  KBMC_REMARKS: [
    "Frequent flight training and glider activity.",
    "SFC unmonitored during night hours."
  ],
  U77_REMARKS: [
    "Obtain local briefing before launch.",
    "Winds shift dramatically."
  ]
};
